name: Build and Deploy Development

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy-dev:
    uses: ornio-no/common-workflows/.github/workflows/hasura-deploy.yml@main
    with:
      env: dev
