name: Build and Deploy Production

on:
  schedule:
    # Set desired time of deploy (UTC)
    # Minute Hour DayOfMonth Month DayOfWeek

    # For Testing Purposes cron timer will be set to 3 minutes
    - cron: "*/3 * * * *"
  workflow_dispatch:

jobs:
  build-and-deploy-prod:
    uses: ornio-no/common-workflows/.github/workflows/cra-build-and-deploy-prod.yml@main
    with:
      image_name: <<IMAGE_NAME>>
    secrets:
      k8s_token: ${{ secrets.DO_TOKEN_PROD }}
      k8s_cluster_id: ${{ secrets.DO_CLUSTER_ID_PROD }}
