name: Build branches

on:
  push:
    branches-ignore:
      - main
  workflow_dispatch:

jobs:
  build-branches:
    uses: ornio-no/common-workflows/.github/workflows/vitejs-build-branches.yml@main
    with:
      node-version: <<NODE VERSION>>
