name: CRA Default Build Branches

on:
    workflow_call:

jobs:
    build:
        name: CRA install and build branch
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
              with:
                  node-version: 'lts/*'
            - name: Install dependencies
              run: npm install
            - name: Run build
              run: npm run build

