name: CRA Release Production

on:
  workflow_call:
    inputs:
      node-version:
        default: "lts/*"
        description: "Node Version"
        required: false
        type: string
    secrets:
      gh_token:
        description: "Github Token"
        required: true
      pat_pkg:
        description: "Personal Access Token for Packages"
        required: true

env:
  GH_TOKEN: ${{ secrets.gh_token }}
  PAT_PKG: ${{ secrets.pat_pkg }}

jobs:
  release-app:
    name: Release the app
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ env.PAT_PKG }}
      - run: git fetch --unshallow --tags
      - uses: actions/setup-node@v2
        with:
          node-version: ${{inputs.node-version}}
          registry-url: https://npm.pkg.github.com/
          scope: "@ornio-no"
      - run: |
          cp .env.prod .env
          npm ci
          npm run build
        env:
          GITHUB_TOKEN: ${{ env.GH_TOKEN }}
          NODE_AUTH_TOKEN: ${{ env.PAT_PKG }}
      - name: Create release
        if: "(!contains(github.event.head_commit.message, 'ci skip') && !contains(github.event.head_commit.message, 'skip ci')) && github.ref == 'refs/heads/main'"
        env:
          GITHUB_TOKEN: ${{ env.PAT_PKG }}
          NPM_TOKEN: ${{ env.PAT_PKG }}
          NODE_AUTH_TOKEN: ${{ env.PAT_PKG }}
        run: npm run release
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: artifact
          path: |
            build/*
            Dockerfile
