name: CRA Default Build Branches

on:
    workflow_call:

jobs:
    build:
        name: Build CRA
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
              with:
                  node-version: 'lts/*'
            - run: |
                  npm install
                  npm run build
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
